# Generated by Django 2.2.11 on 2020-04-09 03:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userworkplace',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='user',
            field=models.ManyToManyField(related_name='workplaces', through='workplace.UserWorkPlace', to=settings.AUTH_USER_MODEL),
        ),
    ]
